"""add message status

Revision ID: d75d3f108943
Revises: 5962dee2485c
Create Date: 2026-10-07 15:47:59.872767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75d3f108943'
down_revision: Union[str, Sequence[str], None] = '5962dee2485c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('status', sa.String(length=20), server_default='complete', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'status')
    # ### end Alembic commands ###
